config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
  }
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  get 'users/index'
  get 'home/index'
  get 'home/chat'
  get 'home/random'
  root to: 'home#index'
  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_left_links_list.html.erb
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
	<%= link_to home_random_path, class: 'nav-link' do %>
		<%= fa_icon 'fw gift' %>
		<%= content_tag :span, 'Random', class: 'nav-link-text' %>
	<% end %>
</li>
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
  <a class="nav-link" href="<%= home_chat_url %>">
    <i class="fa fa-fw fa-keyboard-o"></i>
    <span class="nav-link-text">Chat Online!</span>
  </a>
</li>

app/views/layouts/_top_nav_menu.html.erb
<ul class="navbar-nav ml-auto md">
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-fw fa-envelope"></i>
      <span class="d-lg-none">Messages
        <span class="badge badge-pill badge-primary">12 New</span>
      </span>
      <span class="indicator text-primary d-none d-lg-block">
        <i class="fa fa-fw fa-circle"></i>
      </span>
    </a>
    <div class="dropdown-menu" aria-labelledby="messagesDropdown">
      <h6 class="dropdown-header">New Messages:</h6>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">
        <strong>David Miller</strong>
        <span class="small float-right text-muted">11:21 AM</span>
        <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">
        <strong>Jane Smith</strong>
        <span class="small float-right text-muted">11:21 AM</span>
        <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">
        <strong>John Doe</strong>
        <span class="small float-right text-muted">11:21 AM</span>
        <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item small" href="#">View all messages</a>
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-fw fa-bell"></i>
      <span class="d-lg-none">Alerts
        <span class="badge badge-pill badge-warning">6 New</span>
      </span>
      <span class="indicator text-warning d-none d-lg-block">
        <i class="fa fa-fw fa-circle"></i>
      </span>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
      <h6 class="dropdown-header">New Alerts:</h6>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">
        <span class="text-success">
          <strong>
            <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
        </span>
        <span class="small float-right text-muted">11:21 AM</span>
        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">
        <span class="text-danger">
          <strong>
            <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
        </span>
        <span class="small float-right text-muted">11:21 AM</span>
        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">
        <span class="text-success">
          <strong>
            <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
        </span>
        <span class="small float-right text-muted">11:21 AM</span>
        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item small" href="#">View all alerts</a>
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <% if current_user.cl_image_props %>
        <%= image_tag(current_user.cl_image_props, class: 'avatar', alr: 'user') %>
      <%else%>
        <i class="fa fa-fw fa-user-circle-o"></i>
      <%end%>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
      <h6 class="dropdown-header">Menú Usuario:</h6>
      <div class="dropdown-divider"></div>
      <%= link_to user_path(current_user), class: 'dropdown-item' do %>
        <%= content_tag :span, content_tag(:strong, "#{fa_icon 'fw user'} Perfil".html_safe,{}),{} %>
      <% end -%>
      <div class="dropdown-divider"></div>
      <%= link_to "#{fa_icon 'fw sign-out', class:'align-middle'}Cerrar Sesión".html_safe,
                  destroy_user_session_path, method: :delete, class: 'dropdown-item'  
      %>
      <div class="dropdown-divider"></div>
    </div>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Randomizes !</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="#">Randomizes WebPage</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Inicio">
          <a class="nav-link" href="/">
            <i class="fa fa-fw fa-home"></i>
            <span class="nav-link-text">Inicio</span>
          </a>
        </li>
        <li class="dropdown-divider"></li>
        <!-- left menu links list -->
        <%= render '/layouts/left_links_list' %>
        <!-- end left menu links -->
        <li class="dropdown-divider"></li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <!-- Top Menu -->
      <%= render '/layouts/top_nav_menu' %>
      <!-- end top menu -->
    </div>
  </nav>
	<div class="content-wrapper">
		<div class="container-fluid">
			<!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item <%= ("#{controller_name}_#{action_name}").include?('home_index') ? 'active' : ''%>">
        	<%= link_to "#{fa_icon 'home fw'}Inicio".html_safe, home_index_path %>
        </li>
        <%= content_tag(:li, "#{fa_icon 'fw keyboard-o'}Chat".html_safe, class: 'breadcrumb-item active') if action_name.include?('chat') %>
        <%= content_tag(:li, "#{fa_icon 'fw gift'}RandomPage".html_safe, class: 'breadcrumb-item active') if action_name.include?('random') %>
      </ol>
			<%= yield %>
			<footer class="sticky-footer">
	      <div class="container">
	        <div class="text-center">
	          <small>Copyright © Your Website 2018</small>
	        </div>
	      </div>
	    </footer>
	    <!-- Scroll to Top Button-->
	    <a class="scroll-to-top rounded" href="#page-top">
	      <i class="fa fa-angle-up"></i>
	    </a>
		</div>
	</div>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="awesome webpage">
    <meta name="author" content="Diego AAAAAAAAAAIguilef">
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'login' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'login' %>
  </head>
<body class="bg-dark">
  <div class="container">
    <% card_type = controller_name.include?('sessions') ? 'login' : 'register' %>
    <div class="card card-<%= card_type %> mx-auto mt-5">    
      <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
      <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
      <p id="profile-name" class="profile-name-card"></p>
      <%= yield %>
      <div class="form-group">
        <div class="form-row">
          <div class="col-md-6">
            <%= render "users/shared/links" %>
          </div>
        </div>
      </div>
    </div><!-- /card-container -->
  </div><!-- /container -->
</body>
</html>